package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Tuesday, June 17, 2014 5:40:02 PM ICT
*/

public interface HelloOperations 
{
  String doEcho (String str);
  void shutdown ();
} // interface HelloOperations
