# DO NOT EDIT THIS FILE!
#
# Python module EchoApp__POA generated by omniidl

import omniORB
omniORB.updateModule("EchoApp__POA")

# ** 1. Stub files contributing to this module
import Echo_idl
import Hello_idl

# ** 2. Sub-modules

# ** 3. End
